package academy.pocu.comp2500.assignment2;

public enum Size {
    STAMP_SMALL, STAMP_MEDIUM, STAMP_LARGE,
    CALENDER_WALL, CALENDER_DESK, CALENDER_MAGNET,
    BANNER_SMALL, BANNER_MEDIUM, BANNER_LARGE, BANNER_X_LARGE,
    BUSINESS_CARD
}
